-- ============================================================
-- BUDDICA TOURISM 高松空港店 お問い合わせ管理 DB
-- 那覇/札幌の inquiries 相当を BUDDICA(独立Supabase ggqugvyskyiblxiycpci) に移植
-- Supabase SQL Editor で1回RUN
-- ============================================================

create table if not exists bt_inquiries (
  id               uuid primary key default gen_random_uuid(),
  name             text,
  email            text,
  phone            text,
  inquiry_type     text default 'その他',
  inquiry_content  text,
  status           text default 'new',
  store            text default 'takamatsu',
  source           text,
  received_at      timestamptz,
  gmail_message_id text unique,
  reply_content    text,
  was_edited       boolean default false,
  auto_replied     boolean default false,
  assigned_to      text,
  locked_at        timestamptz,
  created_at       timestamptz default now()
);
create index if not exists idx_bt_inq_status   on bt_inquiries(status);
create index if not exists idx_bt_inq_received on bt_inquiries(received_at desc);

create table if not exists bt_blocked_senders (
  domain     text primary key,
  created_at timestamptz default now()
);

create table if not exists bt_knowledge (
  id         bigint generated by default as identity primary key,
  category   text,
  question   text,
  answer     text,
  priority   int default 100,
  store      text default 'both',
  created_at timestamptz default now()
);

alter table bt_inquiries       enable row level security;
alter table bt_blocked_senders enable row level security;
alter table bt_knowledge       enable row level security;

drop policy if exists bt_inq_all on bt_inquiries;
create policy bt_inq_all on bt_inquiries        for all to anon, authenticated using (true) with check (true);
drop policy if exists bt_blk_all on bt_blocked_senders;
create policy bt_blk_all on bt_blocked_senders  for all to anon, authenticated using (true) with check (true);
drop policy if exists bt_kn_all on bt_knowledge;
create policy bt_kn_all  on bt_knowledge        for all to anon, authenticated using (true) with check (true);
